language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - rbx-2
script: bundle exec rspec spec
notifications:
  recipients:
    - semmons99@gmail.com
    - andreas@aloop.org
    - weppos@weppos.net
